apiVersion: v1
kind: ReplicationController
metadata:
  name: test3
spec:
  replicas: 1
  template:
    metadata: 
      labels:
        app: test3
    spec:
      containers: 
      - name: test3
        image: jupiterpi/test3
        env:
        - name: PORT
          value: "80"
        ports:
        - containerPort: 80