name: Build and push Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.run_number }}
    steps:
    
    - uses: actions/checkout@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    #- name: Extract metadata (tags, labels) for Docker
    #  id: meta
    #  uses: docker/metadata-action@v5
    #  with:
    #    images: my-docker-hub-namespace/my-docker-hub-repository

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64, linux/arm64
        push: true
        tags: jupiterpi/test3:${{ env.IMAGE_TAG }}

    - name: Debug 1
      run: |
        more kubernetes/test3.yaml
        echo ${{ env.IMAGE_TAG }}
        echo "Hey there"
    
    - name: Replace tokens in Kubernetes files
      uses: cschleiden/replace-tokens@v1
      with:
        files: '["kubernetes/*.yaml"]'
      env:
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
    
    - name: Debug 2
      run: |
        more kubernetes/test3.yaml
        echo ${{ env.IMAGE_TAG }}
        echo "Hey there"