name: Build and push Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_push:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build --platform=linux/arm64 --tag jupiterpi/test3 .
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    #- name: Extract metadata (tags, labels) for Docker
    #  id: meta
    #  uses: docker/metadata-action@v5
    #  with:
    #    images: my-docker-hub-namespace/my-docker-hub-repository

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: jupiterpi/test3:latest
