name: Build and push Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.run_number }}
    steps:
    
    - uses: actions/checkout@v3
      
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64, linux/arm64
        push: true
        tags: jupiterpi/test3:${{ env.IMAGE_TAG }}
    
    - uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: "jupiterpi/test3"
        replace: "jupiterpi/test3:${{ env.IMAGE_TAG }}"
        include: "kubernetes/**"

    - name: Debug
      run: |
        more kubernetes/test3.yaml

    - name: Deploy to Kubernetes
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'http://kube-cd.jupiterpi.de/applyKubernetesResource/test3-githubactions/test3.yaml'
        method: POST
        customHeaders: '{"Authorization": "Bearer ${{ secrets.KUBE_CD_TOKEN }}"}'
        contentType: text/plain
        file: kubernetes/test3.yaml